///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2026 Jean-Philippe Steinmetz. All rights reserved.
// SPDX-License-Identifier: MPL-2.0
///////////////////////////////////////////////////////////////////////////////
import MimeNode from "nodemailer/lib/mime-node/index.js";
import { extractHeader } from "./MimeHeaderUtils.js";

/**
 * Generates and parses real RFC 3798 Message Disposition Notifications (MDNs) - the wire format behind both
 * delivery and read receipts (see `ScanQueueJob.maybeSendReceipt()`/`processReceipt()` and
 * `BaseMessageRoute.send()`/its `update()` override). Genuinely standards-compliant on both ends, verified
 * with a throwaway script against real `nodemailer`/`mailparser` behavior before writing this module - so a
 * receipt this library generates is understood by real external mail systems, and a receipt generated by one
 * of *them* is understood here too. This is the one thing that makes the "indicator on the original message,
 * not a separate visible email" mechanism (`ScanQueueJob.processReceipt()`) work uniformly regardless of who
 * generated the receipt.
 *
 * RFC 3798 defines exactly one notification concept, triggered by `Disposition-Notification-To` and reported
 * via a `Disposition:` field whose defined disposition-types include `displayed`/`deleted`/`dispatched`/
 * `processed` - there is no distinct "delivered" concept at the MDN layer (real delivery-status reporting is
 * DSN/RFC 3464, an MTA-level mechanism this content-filter application sits downstream of and has no access
 * to). To still distinguish "delivered to the mailbox" from "read" as two real, protocol-legal signals rather
 * than inventing non-standard vocabulary: **read** receipts use `Disposition: automatic-action/MDN-sent-
 * automatically; displayed`, and **delivery** receipts use `Disposition: automatic-action/MDN-sent-
 * automatically; processed` (RFC 3798's defined type for "acted on by automatic means, not necessarily
 * displayed") - both fully legal RFC 3798 values, sent as two separately-triggered MDNs.
 *
 * @author Jean-Philippe Steinmetz
 */

/** The result of parsing an inbound MDN's `message/disposition-notification` part. */
export interface ParsedDispositionNotification {
    /** The `Original-Message-ID` this MDN is about, angle brackets stripped (matching this library's own
     * `messageIdHeader` normalization everywhere else). */
    originalMessageId: string;

    /** The `Final-Recipient` this MDN's own sender is reporting as - normalized to lowercase. This is what
     * lets `ScanQueueJob.processReceipt()` update the correct row in a sent message's per-recipient
     * `receiptStatus` roster, including for a distribution list's individually-expanded members (each
     * reports its own address, never the list's). `undefined` if the part carries no `Final-Recipient` line
     * at all - a real MDN always should, but this is still usable without it (the caller falls back to
     * appending a new roster row it can't otherwise identify). */
    finalRecipient?: string;

    /** `"read"` if `Disposition` contains `displayed`; otherwise `"delivery"` for any other recognized MDN
     * disposition-type (`deleted`/`dispatched`/`processed`/etc.) - a deliberate, documented fallback so an
     * external system's own exact disposition-type vocabulary still maps to one of this library's two
     * signals rather than being silently dropped. `undefined` if the part carries no `Disposition` line at
     * all (not a real MDN, or too malformed to trust). */
    dispositionType?: "read" | "delivery";

    /** The reporting peer's current encryption-key fingerprint, carried as an RFC 8098 extension field per
     * `specs/end-to-end_encryption.md`'s "Rotation Notification" section (Group E5). **A cache-invalidation
     * hint only** - the spec is explicit that a receiving peer MUST re-run real Discovery
     * (`util/KeyringUtils.ts`'s `discoverAndMergeKeys()`) rather than install this value directly, since an
     * MDN is only hop-authenticated and a forged one could otherwise force a key change. `undefined` if the
     * part carries no such extension field. */
    rotatedKeyFingerprint?: string;

    /** The reporting peer's domain federation policy `id` (`util/FederationUtils.ts`'s cache token), carried
     * alongside `rotatedKeyFingerprint` for the same reason and given the same cache-invalidation-hint-only
     * treatment. `undefined` if the part carries no such extension field. */
    policyId?: string;
}

/**
 * Parses `raw` - the decoded text of an inbound message's `message/disposition-notification` part (see
 * `ScanPipeline`'s private `deriveDispositionNotificationPart()`) - into its `Original-Message-ID`/
 * `Final-Recipient`/`Disposition` fields. Reuses the existing `MimeHeaderUtils.extractHeader()` line-scanner
 * against `raw` directly: a `message/disposition-notification` part is itself just an RFC 822 header block
 * with no body, which `extractHeader()`'s "no blank line found - treat the whole text as headers" fallback
 * already handles correctly.
 *
 * Returns `undefined` if no `Original-Message-ID` can be extracted at all - without it there is nothing to
 * correlate this MDN against, so a partial result would never be useful to a caller (mirrors
 * `ScanQueueJob.processRecall()`'s own "not_found" case, which similarly does nothing further).
 */
export function parseDispositionNotification(raw: string): ParsedDispositionNotification | undefined {
    const buffer: Buffer = Buffer.from(raw, "binary");

    const originalMessageIdHeader: string | undefined = extractHeader(buffer, "Original-Message-ID");
    if (!originalMessageIdHeader) {
        return undefined;
    }
    // `extractHeader()`'s generic unfolding joins a folded continuation line with a literal space, which is
    // correct for ordinary free-text headers but corrupts a `msg-id` token specifically - a real msg-id never
    // legally contains internal whitespace, so any whitespace surviving inside one here can only be unfolding
    // artifact, never real content. Stripped outright (not just trimmed) so a msg-id folded by a non-strict
    // sender's line-wrapping still round-trips to the exact same lookup key `send()` originally stored.
    const originalMessageId: string = originalMessageIdHeader.replace(/^</, "").replace(/>$/, "").replace(/\s+/g, "");

    // `Final-Recipient` is `rfc822;<address>` (RFC 3798 §3.2.3) - possibly with a display name/comment this
    // library never generates itself but a real external MDN might; the address is always the last
    // whitespace-delimited token, which handles both shapes without a full mailbox-syntax parser.
    const finalRecipientHeader: string | undefined = extractHeader(buffer, "Final-Recipient");
    const finalRecipient: string | undefined = finalRecipientHeader
        ?.replace(/^rfc822\s*;\s*/i, "")
        .trim()
        .split(/\s+/)
        .pop()
        ?.replace(/^</, "")
        .replace(/>$/, "")
        .toLowerCase();

    const dispositionHeader: string | undefined = extractHeader(buffer, "Disposition");
    const dispositionType: "read" | "delivery" | undefined = dispositionHeader
        ? dispositionHeader.toLowerCase().includes("displayed")
            ? "read"
            : "delivery"
        : undefined;

    const rotatedKeyFingerprint: string | undefined = extractHeader(buffer, "X-RapidMX-Key-Fingerprint");
    const policyId: string | undefined = extractHeader(buffer, "X-RapidMX-Policy-Id");

    return { originalMessageId, finalRecipient, dispositionType, rotatedKeyFingerprint, policyId };
}

/** The parameters `buildDispositionNotification()` needs to compose one MDN. */
export interface DispositionNotificationParams {
    from: { address: string; displayName?: string };
    to: string;
    subject: string;
    /** This MDN's own sender's address - see `ParsedDispositionNotification.finalRecipient`. */
    finalRecipient: string;
    /** The `Message-ID` (angle brackets optional - always added if missing) of the message this MDN reports
     * disposition for. */
    originalMessageId: string;
    dispositionType: "read" | "delivery";
    /** The `Reporting-UA` value (RFC 3798 §3.2.1) - conventionally `<hostname>; <product name>`. This
     * library reuses its own `mail:dns:mx_hostname` config (already used by `BaseDomainRoute`) as the
     * hostname half. */
    reportingUa: string;
    /** This MDN's own sender's current encryption-key fingerprint, attached as an RFC 8098 extension field
     * per `specs/end-to-end_encryption.md`'s "Rotation Notification" section (Group E5) - omitted entirely
     * when the sending mailbox has no active encrypt key (see `ScanQueueJob.sendDispositionNotification()`).
     * Optional because the underlying spec section is itself a "MAY". */
    rotatedKeyFingerprint?: string;
    /** This MDN's own sender's domain federation policy `id` (`util/FederationUtils.ts`'s cache token),
     * attached alongside `rotatedKeyFingerprint` for the same reason. Not currently populated by this
     * codebase's own MDN-sending path - nothing here tracks this deployment's own outbound `_rapidmx` TXT
     * record's `id` value, which is DNS-admin-managed state this app doesn't own (the same category as
     * `Domain.dkimSelector`) - but accepted and emitted when a future caller does have one. */
    policyId?: string;
}

/**
 * Builds a real RFC 3798-shaped `multipart/report; report-type=disposition-notification` message via
 * `nodemailer`'s lower-level `MimeNode` builder (already a transitive part of the `nodemailer` dependency
 * this library already uses for `MailComposer`) - confirmed with a throwaway script to produce correct
 * boundaries/encoding without hand-rolling MIME multipart construction, unlike `IcsUtils.buildEventIcs()`'s
 * flat, single-part text format, where hand-rolling was the simpler and safer choice.
 */
export function buildDispositionNotification(params: DispositionNotificationParams): Promise<Buffer> {
    const messageId: string = params.originalMessageId.replace(/^</, "").replace(/>$/, "");
    const humanText: string =
        params.dispositionType === "read"
            ? `This message was displayed to ${params.finalRecipient}.`
            : `This message was delivered to ${params.finalRecipient}.`;
    const disposition: string =
        params.dispositionType === "read"
            ? "automatic-action/MDN-sent-automatically; displayed"
            : "automatic-action/MDN-sent-automatically; processed";

    const root = new MimeNode('multipart/report; report-type=disposition-notification');
    root.setHeader("From", params.from.displayName ? `${params.from.displayName} <${params.from.address}>` : params.from.address);
    root.setHeader("To", params.to);
    root.setHeader("Subject", params.subject);
    root.createChild("text/plain").setContent(humanText);
    root.createChild("message/disposition-notification").setContent(
        `Reporting-UA: ${params.reportingUa}\r\n` +
            `Final-Recipient: rfc822;${params.finalRecipient}\r\n` +
            `Original-Message-ID: <${messageId}>\r\n` +
            `Disposition: ${disposition}\r\n` +
            (params.rotatedKeyFingerprint ? `X-RapidMX-Key-Fingerprint: ${params.rotatedKeyFingerprint}\r\n` : "") +
            (params.policyId ? `X-RapidMX-Policy-Id: ${params.policyId}\r\n` : ""),
    );

    return new Promise<Buffer>((resolve, reject) => {
        root.build((err: Error | null, message: Buffer) => {
            /* v8 ignore next 3 -- unreachable in practice: `MimeNode.build()` fails only for a stream source
               it can't read (attachments/content streams, neither of which this module ever supplies - every
               part here is set via `setContent()` with a plain string) - not a real scenario to construct a
               test around, just the standard callback-to-promise error path. */
            if (err) {
                reject(err);
            } else {
                resolve(message);
            }
        });
    });
}
